include:
    # Metadata shared my many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml
    - local: .gitlab/upload.yml

    # OS builds.
    - local: .gitlab/os-linux.yml
    - local: .gitlab/os-macos.yml

stages:
    - build
    - test
    - test-ext
    - upload

################################################################################
# Job declarations
#
# Each job must pull in each of the following keys:
#
#   - a "base image"
#   - a build script
#   - tags for the jobs
#     - already provided for upload and CI update jobs
#   - rules for when to run the job
#
# Additionally, jobs may also contain:
#
#   - artifacts
#   - dependency/needs jobs for required jobs
################################################################################

# Linux

## Basic builds

build:fedora33-mpi-renderless:
    extends:
        - .fedora33_mpi_renderless
        - .cmake_build_linux
        - .linux_builder_tags
        - .cmake_build_artifacts
        - .run_manually

test:fedora33-mpi-renderless:
    extends:
        - .fedora33_mpi_renderless
        - .cmake_test_linux
        - .linux_builder_tags
        - .cmake_test_artifacts
        - .run_automatically
    dependencies:
        - build:fedora33-mpi-renderless
    needs:
        - build:fedora33-mpi-renderless

test-ext:vtk:fedora33-mpi-renderless:
    extends:
        - .fedora33_mpi_renderless_ext_vtk
        - .cmake_test_external_linux
        - .linux_qt_builder_tags
        - .cmake_tidy_artifacts
        - .run_automatically
    dependencies:
        - test:fedora33-mpi-renderless
    needs:
        - test:fedora33-mpi-renderless

# build:fedora33-java-mpi-qt-tbb:
#     extends:
#         - .fedora33_java_mpi_qt_tbb
#         - .cmake_build_linux
#         - .linux_qt_builder_tags
#         - .cmake_build_artifacts
#         - .run_manually
#     # The Java build extends the build time considerably.
#     timeout: 2 hours

# test:fedora33-java-mpi-qt-tbb:
#     extends:
#         - .fedora33_java_mpi_qt_tbb
#         - .cmake_test_linux
#         - .linux_qt_tester_tags
#         - .cmake_test_artifacts
#         - .run_automatically
#     dependencies:
#         - build:fedora33-java-mpi-qt-tbb
#     needs:
#         - build:fedora33-java-mpi-qt-tbb

build:fedora33-mpi-python-qt-tbb:
    extends:
        - .fedora33_mpi_python_qt_tbb
        - .cmake_build_linux
        - .linux_qt_builder_tags
        - .cmake_build_artifacts
        - .run_manually

test:fedora33-mpi-python-qt-tbb:
    extends:
        - .fedora33_mpi_python_qt_tbb
        - .cmake_test_linux
        - .linux_qt_tester_tags
        - .cmake_test_artifacts
        - .run_automatically
    dependencies:
        - build:fedora33-mpi-python-qt-tbb
    needs:
        - build:fedora33-mpi-python-qt-tbb

test-ext:vtk:fedora33-mpi-python-qt-tbb:
    extends:
        - .fedora33_mpi_python_qt_tbb_ext_vtk
        - .cmake_test_external_linux
        - .linux_qt_builder_tags
        - .cmake_tidy_artifacts
        - .run_automatically
    dependencies:
        - test:fedora33-mpi-python-qt-tbb
    needs:
        - test:fedora33-mpi-python-qt-tbb

## Static analysis builds

build:fedora33-tidy:
    extends:
        - .fedora33_tidy
        - .cmake_build_linux
        - .linux_builder_tags
        - .cmake_tidy_artifacts
        - .run_manually
    # clang-tidy really hampers compilation cache improvements, so it takes
    # longer.
    timeout: 2 hours

## Sanitizer builds

build:fedora33-asan:
    extends:
        - .fedora33_asan
        - .cmake_build_linux
        - .linux_qt_builder_tags
        - .cmake_build_artifacts
        - .run_manually

test:fedora33-asan:
    extends:
        - .fedora33_asan
        - .cmake_memcheck_linux
        - .linux_qt_tester_priv_tags
        - .cmake_test_artifacts
        - .run_automatically
    dependencies:
        - build:fedora33-asan
    needs:
        - build:fedora33-asan

build:fedora33-tsan:
    extends:
        - .fedora33_tsan
        - .cmake_build_linux
        - .linux_qt_builder_tags
        - .cmake_build_artifacts
        - .run_manually

test:fedora33-tsan:
    extends:
        - .fedora33_tsan
        - .cmake_memcheck_linux
        - .linux_qt_tester_priv_tags
        - .cmake_test_artifacts
        - .run_automatically
    dependencies:
        - build:fedora33-tsan
    needs:
        - build:fedora33-tsan

build:fedora33-ubsan:
    extends:
        - .fedora33_ubsan
        - .cmake_build_linux
        - .linux_qt_builder_tags
        - .cmake_build_artifacts
        - .run_manually

test:fedora33-ubsan:
    extends:
        - .fedora33_ubsan
        - .cmake_memcheck_linux
        - .linux_qt_tester_priv_tags
        - .cmake_test_artifacts
        - .run_automatically
    dependencies:
        - build:fedora33-ubsan
    needs:
        - build:fedora33-ubsan

## Documentation

build:documentation:
    extends:
        - .fedora33_doxygen_mpi_python_qt_tbb
        - .cmake_build_linux
        - .linux_qt_builder_tags
        - .cmake_doxygen_artifacts
        - .run_manually

upload:documentation:
    extends:
        - .rsync_upload
        - .upload_only
    dependencies:
        - build:documentation
    needs:
        - build:documentation
    variables:
        SRC_SUBDIR: install/usr/share/doc/vtk/doxygen/html/
        RSYNC_DESTINATION: VTKDoxygen/html

# macOS

build:macos-kits-python-qt:
    extends:
        - .macos_kits_python_qt
        - .cmake_build_macos
        - .macos_builder_tags
        - .cmake_build_artifacts
        - .run_manually
    # Some of the macOS runners are not very powerful.
    timeout: 2 hours

test:macos-kits-python-qt:
    extends:
        - .macos_kits_python_qt
        - .cmake_test_macos
        - .macos_builder_tags
        - .cmake_test_artifacts
        - .run_automatically
    dependencies:
        - build:macos-kits-python-qt
    needs:
        - build:macos-kits-python-qt

test-ext:vtk:macos-kits-python-qt:
    extends:
        - .macos_kits_python_qt_ext_vtk
        - .cmake_test_external_macos
        - .macos_ext_builder_tags
        - .cmake_tidy_artifacts
        - .run_automatically
    dependencies:
        - test:macos-kits-python-qt
    needs:
        - test:macos-kits-python-qt
