include("${CMAKE_CURRENT_LIST_DIR}/configure_fedora34.cmake")

set(VTK_GENERATE_SPDX OFF CACHE BOOL "" FORCE)

set(VTK_MODULE_ENABLE_VTK_fides NO CACHE STRING "")
set(VTK_MODULE_ENABLE_VTK_IOADIOS2 NO CACHE STRING "")
set(VTK_MODULE_ENABLE_VTK_IOFides NO CACHE STRING "")
